# Generated by Django 2.1.5 on 2019-02-17 18:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateField()),
                ('to', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('what', models.CharField(max_length=255)),
            ],
        ),
    ]
