# Generated by Django 2.1.5 on 2019-02-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
